### ISSUE TITLE
db password isn't encrypted

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#10]
the b3 database password is plain text. Could that be more secure?

**Comment by MichaelHillcox** [comment]
No unfortunately not. I could do a simple encryption but it would only help a little bit. Id also not want to have to decrypt the db details everytime I want to connect to it. The simplest thing I can think to do is more the config out of the db and put it on a flat file storage system instead. Basically saved in a file instead of the db. There is security implications no matter how you look at the situation

**Comment by wassie** [comment]
agreed. I just noticed it, and you are the developer and call the shots :)

**Comment by MichaelHillcox** [comment]
Personally I feel like moving it outside of the database would be an added (small) layer of security to stop people getting database access if they find a way to dump the database. I'll look into it :)

**Comment by MichaelHillcox** [comment]
As of 799f20f we no longer store the b3 database's details inside of the echelon database. This is a pretty big change and will require anyone using this version of echelon to follow this wiki page
https://github.com/MichaelHillcox/Echelon/wiki/Migrating-from-an-old-b3-instance
