### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by wassie** [MichaelHillcox/Echelon#3]
hi Michael,

Is there a new or updated version of Echelon? Are you still developing? I'm really curious about your progress.

**Comment by MichaelHillcox** [comment]
@wassie Logically the master branch is just development at this point. I don't want people running experimental code. I've not made any changes to database structure or to how the core functionality of echelon work. Therefor if you wanted to. You could pull down my code and deploy it using an existing branch. Although clearly, I would not support this idea because its all experimental. Basically use at your own risk. I will be creating release as soon as the reskinning is done. Unfortunately paid projects have to take priority. 

Of course you still have the [change Log](https://github.com/MichaelHillcox/Legacy-Echelon/blob/master/ChangeLog.md) if you want to see what I've been up to. I'm thinking about setting up github pages as a blog / dev blog to show off the new stuff.

It's great to hear that people are still interested in the project :).

**Comment by wassie** [comment]
@MichaelHillcox great it still has your attention! :)
Is there a fund that I can use to encourage in this project?

**Comment by MichaelHillcox** [comment]
@wassie not as of this moment no. I've got some paid work that's taking a lot of my time up :P I'm available for paid work if you need specific things done to your echelon /sites. What do you use echelon for (game)?

**Comment by wassie** [comment]
@MichaelHillcox,  good old Call of Duty United Offensive. 
The things that I would like are already in the issues. But I guess that I can't affort you for hiring you for making Echelon better

**Comment by MichaelHillcox** [comment]
Well this iteration of echelon is going to be a lot better than the last one. Im looking at a stable build very soon. Could you possibly duplicate your b3 database and empty the columns with sensitive data? I only have cod4 to test against at the moment.

**Comment by wassie** [comment]
hi Michael, did you make any progress last months on the new Echelon?

**Comment by MichaelHillcox** [comment]
@wassie I've taken on Echelon v2 as my main development branch and I've been working on a cleaner and much easier to use interface. If you want you can pull my master branch and load it up on one of your databases ( Please be sure to dupe your echelon and b3 database and use the copies instead of your production ones ). Currently not much has changed under the hood. I've moved some things into legacy / deprecated mode but thats about it. 

You can see my full [change log here](https://github.com/MichaelHillcox/Echelon/blob/master/ChangeLog.md) which I tend to outline in quite a lot of detail. I've moved the whole site over to bootstrap but it's been taking quite some time. 

Here are some images of the face lift. [Imgur](http://imgur.com/a/wFdU8)

**Comment by wassie** [comment]
great @MichaelHillcox , looks really good :)
I got a test server running so I could try to test it on my test environment! So I can just pull it and install it? Or do I need to take care of creating tables or anything?

**Comment by MichaelHillcox** [comment]
@wassie Just use an already existing database ( echelon database ). You can run the installer but you'll have to modify the config to make sure installed != true or what ever. :)

**Comment by wassie** [comment]
@MichaelHillcox for my production environment I created a single database outside of my game server, and therefor outside of the B3 database. From that domain I connect to the game server and read the B3 table. Is this also possible with this version?

**Comment by MichaelHillcox** [comment]
So you have a second server for your mysql stuff? hit me up on Discord (MiKeY
#3704), Steam ( http://steamcommunity.com/id/aokmikey ), or my email. ( hello.michaelhillcox@gmail.com / mikey@pxg.me ). Take a pick. Of course DM's are much faster. I can help you through getting it set up to use and play around with.
