### ISSUE TITLE
xlrstats public table

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#31]
Hello sir i was wondering if you could make an xlrstats tables like the public banlist it would be better 
Also give us more options to edit the panel like adding players map "Geo Map" to change permissions so guest can see them without registering and be added to list like public banlist

**Comment by wassie** [comment]
good suggestion!

**Comment by MichaelHillcox** [comment]
So just public XLRStats? if so then the guys at b3 who created XLR also have their own web based system for showing each players XLRStats

**Comment by wassie** [comment]
yes, that webbased tool could work too, but its difficult to integrate it in a website, because its a stand alone application.

**Comment by wassie** [comment]
maybe not the right place to ask, but are there some new things that I can test?

**Comment by Skillz7z** [comment]
Well thanks for the interest in my idea 
i think you know this panel ? http://cod4-server.info/ 
an echelon and xlrstats 
@MichaelHillcox 

I have to remind you if you want to attach the XLRstats you have to read this 
As am hosting many servers for the same clan am using same Database but different XLRstats tables per server like 28960_xlr_body... 28961_xlr_body and so ...

I wish you have understood me

So it must have options to edit which tables you have to display just like the XLRstats webfront that we know 

And am really glad to see your work man you are a legend keep it up sir

**Comment by Skillz7z** [comment]
Actually i have many suggestions that make life easier while using this web front 
Like adding games from website not like we do usually now go to config and stuff like this adding multi games and adding database connection for the game from the website no need to open configs ...

**Comment by Skillz7z** [comment]
One more thing am using a subdomain *echelon.xtreme-gaming.co* and inside that subdomain 2 folders "2 Echelons" *xg , orion* When i logout from one of them it send me back to *echelon.xtreme-gaming.co/login.php* why this happen ? why i does not send me to echelon.xtreme-gaming.co/xg/login.php

**Comment by Skillz7z** [comment]
I found another problem in registering ... the problem is you have to fill all the fills even if u have registering key ... and if you don't have you have to put one even if its only normal register ...

**Comment by MichaelHillcox** [comment]
@Skillz7z I understand your want for the XLR stats but as it's only designed to be a plugin for b3 I can't justify changing a large amount of the Echelon code base to support the sort of system you are explaining. The website you've provided above is one I've seen before, from what I can tell it's simply just a system build upon the b3 database. It's a slimed down version of echelon. It's some what interesting but when you remove the Echelon Code base and need to keep the system backwards compatible you run into a lot of issues with doing such a large rewrite. 

The XLRStats site is currently the only thing I can suggest to you but I can understand the want for a webfront that is able to give a public facing stats list and other such things. With XLRStats webfront please note that you don't need to have an account. You can watch your player or other players simply by watching that specific b3 ID. Unfortunately the world we live in, CoD4 and a few other games have GUID tags that can simply be changed with a different cd key or a few other little things. So we tend to find that it's very hard to keep track of players because of this. On my servers, 98% of our players at some point have used a different GUID with the same IP. So going by this you can probably see how it becomes a difficult challenge to track players stats making any such system a waste of time :P 

As for you bug, could you start a new ticket and show the URL you're having the issue on and possibly some screenshots too. Thanks :P

**Comment by Skillz7z** [comment]
Yea i understand you but it was a suggestion not more and again am telling you i like your project

**Comment by wassie** [comment]
hi Michael, did you made any progress with the Echelon project?

**Comment by MichaelHillcox** [comment]
A little :P I've been messing with it but I've been focusing on different tech at the moment. I'm thinking that if I was to remake the project using a js framework with a simple php restful backend then we could achive a really quick user interface ( website ) and an even quicker backend whist having the benefit of a clean codebase :D This is just an idea but I want to use vue more so I might try that for this project. Echelon needs to be rewritten so baddly. The code is aweful :P

**Comment by wassie** [comment]
if it's awful, I can understand your wish to rewrite it. I have just a little coding knowledge, so I can't judge it at all. I really hope this project comes to live and will succeed one of these days. The current version of Echelon is so limited.

**Comment by MichaelHillcox** [comment]
@wassie My thinking at this point is that I want to completely redo Echelon to extend it's functionality. So, for me to do that, I need a solid plan for what the next Echelon will do. Would you like to hit me up at any of the follow social links https://mikey.pro ( They're all there ) so we can descuss what a possible future echelon might be made up of? Would be great to have a chat. 

Anyone else watching this repo is also welcome to message me and have a chat :D

**Comment by MichaelHillcox** [comment]
Okay, I'll do it. I'll add a public xlrstats place :P

**Comment by wassie** [comment]
I just poked you on Skype :)
