### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#32]
Hello @MichaelHillcox am going to list for you some bugs or maybe idk but i see them bugs xD 

Registering : 
First \\ When you create new register key and an "E-mail" passed on that key you just have to put it in two fields these fields are the place where you have to put the key and email if exist so now (If exist you just put them and pass the webpage but no the other field that about "If you don't have a key" is required) here i just deleted the line where it says its required take this for example 
`
					<div class="form-group">
						<label for="key">Registration key:</label>
						<input type="text" maxlength="40" size="40" class="form-control" 
						 name="key" tabindex="1" _required_ />
					</div>`

Second \\ when you make a register key and an "E-mail" passed on that key and try to register with it it will always says invalided email i don't know why but that's what happening with me 

Wrong Directory:
--->> \\ I have created two echelons and ran them in a subdomain called _echelon.xtreme-gaming.co_ in two folders xg and orion now when you login to xg or orion and want to logout it drives you to _echelon.xtreme-gaming.co/login.php_ when you logout that confused me little because i thought the home directory for the echelon is itself folder but i fixed it by removing this ((../)) and it just worked idk is this is a right thing to do because i don't know anything about php i just was trying to find out some problems and solve them xD 
`if( isset($_GET['logout']) ) {
	$auth_name = 'login';
	require 'inc.php';

	$ses->logout(); // logout user
	send('**../**login.php'); // send back to login back
}`

Now here some suggestion for you idk some of them suggested before by me and others i really can't remember but read it out if possible 

Creating Games: 
First \\ Make the panel support multi games not only just one game

Second \\ Make adding games and game database from browser no need to edit the config.php to add the ID and the the database info from there

Console page:
Maybe idk about this if you could add a console commands per server ? idk i just thought about this now xD 

Geo map: 
I suggested this before 
Add the Geo Map in public so no-one need to register or login to see the map 

Online Players:
Maybe you can add players who is online 

Thats all for now but please tell me if i did the right about the problems up there and fix the registering stuff

**Comment by MichaelHillcox** [comment]
Thanks for this. I will have a look and try to see what is causing some of these issues. I've not got a huge amount of time at the moment but I will do it some time soon. 

As for your suggestions:
1. Not really sure on what you mean here? You make a game and then add servers to it. I'm not sure on why you'd want to have more than one game under a game? or do you want it so you can create them faster? I'm not really sure on what you're asking for here.
2. No? This was done to prevent there being only one point of failure. Sure someone could get into your mysql DB if the password was crap but they'd have to get into your server instance to find your B3 Passwords. This was simply a security measure to try and avoid possible fuck ups. Although, Soon enough, I will be making the system able to create and modify that config files for you so... yes and no. :P 
3. This has some pretty big security concerns. It would also be slow and somewhat a waste of time. Logically it would always be best to login to the server and check the console. I've not explored the RCON protocol that much but I don't know if it would handle the response probably. if you can find an instance of someone else doing this on Github then I'd be happy to take a look at the code and see about implementing it.
4. Giving out players possible locations is really not something you should do without their consent. I personally feel you shouldn't even see their IP but thats just me. I can maybe make it a config option but I was pretty sure I removed the GEO map.... * Correction * no I haven't but I will be due to the link provided is to a paid service. 
5. I could. I'll think about it.

**Comment by Skillz7z** [comment]
> Not really sure on what you mean here? You make a game and then add servers to it. I'm not sure on why you'd want to have more than one game under a game? or do you want it so you can create them faster? I'm not really sure on what you're asking for here.

What am telling here is to add more than on database for more servers ... 
Like add two databases one for public server and another for a private server 

Well all the above is good to me xD but did not understand the geo map about ** i will be due to the link provided is to a paid service**

**Comment by Skillz7z** [comment]
and btw whats the point of adding servers ?

**Comment by Skillz7z** [comment]
also @MichaelHillcox Please take a look on this PLZ [http://prntscr.com/hc3ob9](url)
It annoys me really ........

**Comment by MichaelHillcox** [comment]
@Skillz7z I can't fix it without knowing the error. Please sure that you have your php errors switched on so I can see what the problem is with that part of the site. Please can I also confirm that you're not using this version as a production ready site? this should not be deployed in the public's domain yet. We are still in an untested and unstable stage of development.

**Comment by Skillz7z** [comment]
@MichaelHillcox  tell me exactly what logs do you want ? so i just search and pickup the logs for you ?

**Comment by MichaelHillcox** [comment]
@Skillz7z It would seem that you don't know how Echelon is designed to be used... Which is understandable. It's not my software originally but here is a quick tutorial on how to add servers.

We have a game -> server relation. A single game, lets say CoD4 can have a game in Echelon, You can give it a name like "Public CoD4". Once you've created your game, You will then add your servers with their RCON info etc. This allows you to have all your servers under one game and it's b3 database. You should only have one b3 database per game. So one for CoD4 and one for Battlefield and the etc. 

> Right, so while writing this I saw your issue. A single game is meant to be your main b3 database. From this you can run multiple b3 instances off of the one main database. For most cases you should only ever have one b3 database. For chat logs, XLR data and the etc. You can simply prefix or suffix a new table and tell b3 to use the different table to keep the data to their own server. I do get what you mean though. I will add a way to assign a custom database to specific servers in the future.

**Comment by MichaelHillcox** [comment]
To enable php errors please follow this 
https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display#answer-21429652
Then screenshot me the same page with it's error. If no errors show then It'll be something else.

**Comment by Skillz7z** [comment]
well display_errors already on but it does not show any thing

**Comment by Skillz7z** [comment]
@MichaelHillcox well bro i noticed that i have added another game and edited the game ID and kept the same DB Username and password that worked but when i back to the old ID it give database error again

**Comment by MichaelHillcox** [comment]
check the ID of your other game. When you click the drop down and click on your first game your game ID will show up in the URL something like `&game=GAMEIDHERE` if you see the game ID go and check if you've also added that one into your config. I do agree. It's a bitch of a process at the moment but without the time at the moment, I can't improve it. The system isn't ready for use at the moment anyway

**Comment by MichaelHillcox** [comment]
@Skillz7z I'll look into the issue with XLR

**Comment by Skillz7z** [comment]
@MichaelHillcox Thanks bro i will keep you up-to-date for any other problems so we can get the official release asap 💯

**Comment by MichaelHillcox** [comment]
@Skillz7z I've forgotten what I was doing with this. Could you pull my latest code and see how many of the above things are still an issue. Thanks :D
