### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Skillz7z** [MichaelHillcox/Echelon#33]
Hello sir :) 
It's me again 
I was wondering why the heak should echelon has that anti hack shit ... like get locked if 3 failed logins xD if he failed to login then he will never login xD 

Also if you opened multi windows it will warn you as a hacker plz dude ... u are a cod4 player and host ur servers i guess u use one million window in same browser xD 

Also i suggest u to add this i got it from google websites its for auto importing the sql file 
Tell me what do you think ?
```
	$command='mysql -h' .$db_host .' -u' .$db_user .' -p' .$db_pass .' ' .$db_name .' < ' .'echelon.sql';
	$output=array();
	exec($command,$output,$worked);
	switch($worked){
    	case 0:
        echo 'Import file <b>' .'echelon.sql' .'</b> successfully imported to database <b>' .$db_name .'</b>';
        break;
    	case 1:
        echo 'There was an error during import.';
	break;
	}
```

One more thing bro 
Just let us add the b3 information from website not need to edit config.php ...

**Comment by MichaelHillcox** [comment]
I hate the fact that things like that can be done in php. No web language should have system executing abilities and this is no exepetion. I won't be implementing that form of it but seeing as the db is so small and simple, I'll just end up hard coding it or even simpler, Reading the code from the sql file and running the correct query commands to make said things happen. It'll give me a much better way to handle issues.

As of a few months ago, I've completely removed people being locked out but I still don't have a stable alpha / beta release and due to some recent issues I've found with the core system I'm not sure if I ever will get one. I have every intention of doing so though. 

I'm gunna be refactoring my solution for b3 database info. I'm gunna try to do it based on a json file instead and doing it that way will give me a very simple way to allow people to edit them within the website but still not have the data stored on the database. It's a security thing more than anything else. You wouldn't put your passwords on a notepad now would you? They need to be hidden at least if we can't encrypt them.
